[tool.poetry]
name = "dsco"
version = "0.1.1"
description = ""
authors = ["Aaron Palumbo <aaron.palumbo@teradata.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "^5.1"
cookiecutter = "^1.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
rope = "^0.14.0"
pylint = "^2.4"
black = {version = "^18.3-alpha.0", allows-prereleases = true}

[tool.poetry.scripts]
dsco = "dsco.application:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

