FROM {{ cookiecutter.python_version }}-slim as base

COPY . /srv

SHELL ["/bin/bash", "-c"]

RUN pip install ansible toml


FROM base as prod

SHELL ["/bin/bash", "-c"]

RUN cd /srv/builder/ansible && ansible-playbook build_prod_container.yml

