FROM python:{{ cookiecutter.python_version }}-slim as base

COPY . /srv

SHELL ["/bin/bash", "-c"]

RUN pip install ansible toml

FROM base as dev

SHELL ["/bin/bash", "-c"]

RUN cd /srv/builder/ansible && ansible-playbook build_dev_container.yml

