version: '3.7'
services:
   dev:
      build: 
        context: .
        dockerfile: ./builder/Dockerfile_dev
        target: dev
        labels:
          # use com.docker.compose.project=project_name
          # use com.docker.compose.service=dev
          - "com.teradata.dsco=True"
      ports:
        - "{{ cookiecutter.project_port }}:80"
      volumes:
         - ./:/srv
      init: true
      stdin_open: true
      tty: true
   prod:
      build:
        context: .
        dockerfile: ./builder/Dockerfile_prod
        target: prod
        labels:
          # use com.docker.compose.project=project_name
          # use com.docker.compose.service=dev
          - "com.teradata.dsco=True"
      ports:
        - "{{ cookiecutter.project_port|int + 1000 }}:80"
      init: true
      stdin_open: true
      tty: true
   debug:
      build: 
        context: .
        dockerfile: ./builder/Dockerfile_dev
        target: base
        labels:
          # use com.docker.compose.project=project_name
          # use com.docker.compose.service=dev
          - "com.teradata.dsco=True"
      ports:
        - "{{ cookiecutter.project_port|int - 500 }}:80"
      volumes:
         - ./:/srv
      init: true
      command: bash -c "bash"
      stdin_open: true
      tty: true
